image: node:latest

stages:
  - mirror
  - docker-build

mirror:
  stage: mirror
  script:
    #github
    - USERNAME=pektin-dolly
    - git config --global user.email "runner@${CI_SERVER_HOST}"
    - git config --global user.name "runner"
    - git remote remove origin
    - git remote add origin https://${USERNAME}:${GITHUB_TOKEN}@github.com/pektin-dns/${CI_PROJECT_NAME}.git
    - git push --set-upstream origin HEAD:refs/heads/main -f || true
    #gitlab
    - git remote remove origin
    - git remote add origin https://${USERNAME}:${GITLAB_TOKEN}@gitlab.com/${CI_PROJECT_PATH}.git
    - git push --set-upstream origin HEAD:refs/heads/main -f

docker-build:
  stage: docker-build
  image: docker:latest
  before_script:
    - docker login -u "pektin" -p "$CI_REGISTRY_PASSWORD"
  script:
    - docker build --pull -t "pektin/rust-wasm-builder" .
    - docker push "pektin/rust-wasm-builder"
